# Generated by Django 2.2.18 on 2022-06-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_textdatamodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextDataModel',
        ),
    ]
