# Generated by Django 2.2.18 on 2022-06-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_auto_20220628_0216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextDataModel',
        ),
    ]
